version: '2.3'
services:
  web:
    build: .
    command: ["npm", "run", "dev"]
    volumes:
      - ./webapp:/home/node/webapp
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      mongodb:
        condition: service_started
    init: true
    environment:
      MONGO_URL: mongodb://mongodb:27017/Todo

  mongodb:
    image: mongo:3.6.3-jessie
    init: true
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_USER: todoapp
      MONGO_PASS: todos
    ports:
      - "127.0.0.1:27017:27017"

volumes:
  mongo_data: